### ISSUE TITLE
Is there a written out spec for the binary format?

### ISSUE THREAD

**Issue by bowbahdoe** [taoensso/nippy#147]
Forgive me if i'm just not finding it, but is there a spec for the binary format similar to https://download.java.net/java/early_access/panama/docs/specs/serialization/index.html ?

I'm looking to implement a binary EDN sort of thing in Rust and I don't see any reason to re-invent a data format

**Comment by ptaoussanis** [comment]
@bowbahdoe Hi Ethan,

No, there's unfortunately no formal written spec at the moment.
But the format is stable, _reasonably_ simple, and shouldn't be too difficult to understand from reading the codebase.

The details depend very much on what your objectives are. Would your intention be to actually have binary data compatibility between Rust and the JVM? Or you're just looking for inspiration?

Binary data compatibility would likely be non-trivial to tough [1]. Nippy was never designed to be a format portable between platforms. Its design tradeoffs emphasise performance and simplicity of [JVM] implementation over portability. If the goal is portability, a different approach may be sensible.

The meat of Nippy's data format is actually provided by `java.io.DataOutput` and `java.io.DataInput`. Nippy's mostly a thin wrapper around these - mostly to add Clojure type information. Some limited use is also made of `java.io.Serializable`.

If you let me know in more detail what you're hoping to achieve, I can try advise better.

Cheers!

[1] Will depend mostly on whether your target platform already has [/library] support for the `java.io.DataOutput` formats.

**Comment by ptaoussanis** [comment]
@bowbahdoe Hi Ethan, just following up on this. `[com.taoensso/nippy "3.3.0-alpha2"] now contains a new [var](https://github.com/ptaoussanis/nippy/blob/a2e03bef5e3aaabb1351367085334cf8feadcd06/src/taoensso/nippy.clj#L258) that includes some basic info re: Nippy's types.

Not sure how helpful this'd be in your case, since I expect that the bulk of the work for getting something a Rust implementation working would be in matching the `java.io.DataOutput`/`java.io.DataInput` formats.

In any case, the type [spec](https://github.com/ptaoussanis/nippy/blob/a2e03bef5e3aaabb1351367085334cf8feadcd06/src/taoensso/nippy.clj#L94) is now more readable - so should hopefully give you a better idea of what's involved.

But please do let me know if you think of anything else that I/Nippy might be able to provide to make your objective easier.

Cheers!

**Comment by bowbahdoe** [comment]
@ptaoussanis Thanks a lot man! This has circled in the infinite backlog of my stuff so it will be a bit before i give it another go, but this is useful

**Comment by ptaoussanis** [comment]
Closing to focus discussion at https://github.com/taoensso/nippy/issues/151
